//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS35
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Sub industry.
    /// </summary>
    // *** Start programmer edit section *** (SubIndustry CustomAttributes)

    // *** End programmer edit section *** (SubIndustry CustomAttributes)
    [AutoAltered()]
    [Caption("Sub industry")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SubIndustryE", new string[] {
            "Name as \'Name\'"})]
    [View("SubIndustryL", new string[] {
            "Name as \'Name\'"})]
    public class SubIndustry : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (SubIndustry CustomMembers)

        // *** End programmer edit section *** (SubIndustry CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (SubIndustry.Name CustomAttributes)

        // *** End programmer edit section *** (SubIndustry.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (SubIndustry.Name Get start)

                // *** End programmer edit section *** (SubIndustry.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (SubIndustry.Name Get end)

                // *** End programmer edit section *** (SubIndustry.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SubIndustry.Name Set start)

                // *** End programmer edit section *** (SubIndustry.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (SubIndustry.Name Set end)

                // *** End programmer edit section *** (SubIndustry.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SubIndustryE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SubIndustryE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SubIndustryE", typeof(IIS.ISS35.SubIndustry));
                }
            }
            
            /// <summary>
            /// "SubIndustryL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SubIndustryL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SubIndustryL", typeof(IIS.ISS35.SubIndustry));
                }
            }
        }
    }
}
